name: Quarkus, MongoDB and Mosquitto

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Start MongoDB container
      uses: docker://mongo
      env:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password

    - name: Start Mosquitto container
      uses: docker://eclipse-mosquitto

    - name: Build and Run Quarkus Application
      run: |
        mvn clean install
        java -jar target/quarkus-app.jar
